spring:
  application:
    name: jwtauthentication
security:
  jwt:
    issuer: demo-jwt-authentication
    expiration-minutes: 15
    key:
      public: classpath:rsaKey.public
      private: classpath:rsaKey.private